//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template.Core.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VideoPickerPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VideoPickerPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Template.Core.Resources.Localization.VideoPickerPage", typeof(VideoPickerPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string BtnBrowse {
            get {
                return ResourceManager.GetString("BtnBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Video to Play.
        /// </summary>
        public static string BtnCustomPick {
            get {
                return ResourceManager.GetString("BtnCustomPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Random Video.
        /// </summary>
        public static string BtnRandomVideo {
            get {
                return ResourceManager.GetString("BtnRandomVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed file extensions.
        /// </summary>
        public static string LblFilters {
            get {
                return ResourceManager.GetString("LblFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (list them seperated by commas, for example: mkv, mp4).
        /// </summary>
        public static string LblFiltersInfo {
            get {
                return ResourceManager.GetString("LblFiltersInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder with videos.
        /// </summary>
        public static string LblFolder {
            get {
                return ResourceManager.GetString("LblFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (pick the folder that contains videos, doesn&apos;t matter if they are inside other folders).
        /// </summary>
        public static string LblFolderInfo {
            get {
                return ResourceManager.GetString("LblFolderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full screen.
        /// </summary>
        public static string LblFullScreen {
            get {
                return ResourceManager.GetString("LblFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string LblOptions {
            get {
                return ResourceManager.GetString("LblOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string LblSeconds {
            get {
                return ResourceManager.GetString("LblSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time:.
        /// </summary>
        public static string LblStartTime {
            get {
                return ResourceManager.GetString("LblStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VLC player exe file location.
        /// </summary>
        public static string LblVlcLocation {
            get {
                return ResourceManager.GetString("LblVlcLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a video to play.
        /// </summary>
        public static string TitleCustomVideo {
            get {
                return ResourceManager.GetString("TitleCustomVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick VLC player&apos;s location.
        /// </summary>
        public static string TitleVlcLocation {
            get {
                return ResourceManager.GetString("TitleVlcLocation", resourceCulture);
            }
        }
    }
}
